### ISSUE TITLE
免流还是什么？

### ISSUE THREAD

**Issue by xtyzhen** [q792602257/Learning#1]
兄弟我为什么在你的文件里找到了沃商店的ss免流地址，兄弟你这个程序是干什么的。

**Comment by q792602257** [comment]
你说的是这个<a href="https://github.com/q792602257/Learning/blob/master/Python/wxPython/p.py">p.py</a>嘛，这个是我给一个朋友做的一个小程序，能够解析SS/SSR链接的工具，里面注释的链接只是他发过来我做解析测试用的
